export const SIGN_IN = '/signin'
export const SIGN_OUT = '/signout'
export const USERS = '/users'
export const USERS_INFO = '/users/user-info'
export const USERS_RESET_PASSWORD = '/users/reset-password'